name: Profile metrics
on:
  schedule:
    - cron: "0 9 * * 1"   
  workflow_dispatch:

permissions:
  contents: write   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} 
          user: FernandoAbishai
          template: terminal
          base: header, repositories
          config_timezone: America/Tijuana
          repositories: 100
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          filename: metrics.svg         
          committer_branch: main        
          output_action: commit
